### PR TITLE
feat: update to support Lux 1.0

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by facusapienza21** [comment]
Thank you @avik-pal for the PR! 

I am going to start working in a new branch with Lux 1.0 and see how it works. The new features look very good, so I will try to implement them there. Now I am about to make a PR with the stable version of Lux 0.5. 

This current PR breaks the package. I think the reason for this is that I am using a customized activation function, for which I should be using `AbstractLuxLayer`([docs](https://lux.csail.mit.edu/stable/api/Building_Blocks/LuxCore#LuxCore.AbstractLuxLayer)), right? I did a quick test of this and it didn't work, if you have any example that you can point out, I would really appreciate it. With the changes you suggested, I was getting this same [error](https://github.com/LuxDL/Lux.jl/issues/743), even when working on Lux 1.0

I will try nested AD in the future, that looks like a really nice feature. 

Looking forward for the new advances in Lux!

**Comment by facusapienza21** [comment]
Looking at the [docs](https://lux.csail.mit.edu/stable/manual/nested_autodiff), I am wondering if the nested AD feature will work with this customized layers. This is a feature we currently have but using complex-step differentiation or finite differences, and I would really like to use pure AD for the differentiation of the NN with this customized layers.

**Comment by avik-pal** [comment]
> This current PR breaks the package. I think the reason for this is that I am using a customized activation function, for which I should be using AbstractLuxLayer([docs](https://lux.csail.mit.edu/stable/api/Building_Blocks/LuxCore#LuxCore.AbstractLuxLayer)), right?

Can you point me to the code?

> Looking at the [docs](https://lux.csail.mit.edu/stable/manual/nested_autodiff), I am wondering if the nested AD feature will work with this customized layers.

It will as long as you subtype it with AbstractLuxLayer and remember to wrap it with StatefulLuxLayer before calling the gradient functions. If you have a link I can take a look, most likely it is missing a wrapper here.

**Comment by facusapienza21** [comment]
Well right now I am not even able to solve the environment... I pull your changes to [my fork](https://github.com/facusapienza21/SphereUDE.jl.git) for development, you can see there that the [CI is not working](https://github.com/facusapienza21/SphereUDE.jl/actions/runs/11076190294/job/30778748159) and cannot precompile the libraries. I managed to make this work yesterday, but I think maybe I was using a different Project.toml. 

I have a quite different error when instantiating the libraries in local, which is this: 

image

Do you think this can be a compatibility issue coming from Lux @avik-pal ?

**Comment by avik-pal** [comment]
use 1.10 or above. 1.9 won't install any SciML or Lux packages

**Comment by facusapienza21** [comment]
@avik-pal for the julia version you mean? This is currenly using Julia 1.10

**Comment by facusapienza21** [comment]
Keeps failing. :( 

There is an issue with CI coming from `OrdinaryDiffEq` in the test, but the real problem comes before with 
```
Error: Error during loading of extension DiffEqBaseEnzymeExt of DiffEqBase
```
This is the same error I have in local, unclear where is it coming from.

**Comment by avik-pal** [comment]
Bad diffeqbase release, but that should be harmless in this context. Need to see what is keeping Enzyme at 0.12.

**Comment by facusapienza21** [comment]
Did some new release come up in the last 24hrs? This was working yesterday at least in local.

**Comment by facusapienza21** [comment]
@avik-pal I just solved this by fixing `Lux=1.0`. Maybe something broke with `v1.1`? I am going to merge a PR with this changes to the branch `up-lux` so we can both PR (I merged your changes in my fork, so you should figure in the PR).

**Comment by avik-pal** [comment]
Yeah I screwed up a release :sweat: https://github.com/JuliaRegistries/General/pull/116180. Was handling too many PRs and this happened.

I will dig into this over the weekend, the other issue that came up is Enzyme also had a breaking change to 0.13 which changes API so we had to hard bound it in 1.1. So that is very likely the issue that you are seeing

**Comment by facusapienza21** [comment]
Ok, thank you for taking care of this @avik-pal 

Should I wait until the next release of Lux to try this or do you think I can move forward with Lux=1.0 and try also the nested AD? I have no immediate rush, so I can wait for the next one.

**Comment by avik-pal** [comment]
Tested locally it should now be fixed. Closures are unfortunately bad and cause weird issues when used inside hot loops.

**Comment by facusapienza21** [comment]
Thank you @avik-pal ! I hope this works! 

Would you make me the favor of opening this PR in the branch `up-lux`? I would prefer not to touch the `main` branch yet.

**Comment by avik-pal** [comment]
yeah sure

**Comment by facusapienza21** [comment]
Test passing @avik-pal ! Great. If you open the PR on `up-lux` with these changes I can merge to the main repo. I would like to do a few more things with the new version of Lux before merging to main.

**Pull request merged**
